#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Food")]
	public partial class ProductDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public ProductDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FoodConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _food_id;
		
		private string _food_name;
		
		private decimal _food_price;
		
		private string _food_image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfood_idChanging(string value);
    partial void Onfood_idChanged();
    partial void Onfood_nameChanging(string value);
    partial void Onfood_nameChanged();
    partial void Onfood_priceChanging(decimal value);
    partial void Onfood_priceChanged();
    partial void Onfood_imageChanging(string value);
    partial void Onfood_imageChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_food_id", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string food_id
		{
			get
			{
				return this._food_id;
			}
			set
			{
				if ((this._food_id != value))
				{
					this.Onfood_idChanging(value);
					this.SendPropertyChanging();
					this._food_id = value;
					this.SendPropertyChanged("food_id");
					this.Onfood_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_food_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string food_name
		{
			get
			{
				return this._food_name;
			}
			set
			{
				if ((this._food_name != value))
				{
					this.Onfood_nameChanging(value);
					this.SendPropertyChanging();
					this._food_name = value;
					this.SendPropertyChanged("food_name");
					this.Onfood_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_food_price", DbType="Decimal(5,2) NOT NULL")]
		public decimal food_price
		{
			get
			{
				return this._food_price;
			}
			set
			{
				if ((this._food_price != value))
				{
					this.Onfood_priceChanging(value);
					this.SendPropertyChanging();
					this._food_price = value;
					this.SendPropertyChanged("food_price");
					this.Onfood_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_food_image", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string food_image
		{
			get
			{
				return this._food_image;
			}
			set
			{
				if ((this._food_image != value))
				{
					this.Onfood_imageChanging(value);
					this.SendPropertyChanging();
					this._food_image = value;
					this.SendPropertyChanged("food_image");
					this.Onfood_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
